// src/utils/mapConstants.js
const mapTilerKey = import.meta.env.VITE_MAPTILER_API_KEY?.trim();
const mapTilerLightStyle = import.meta.env.VITE_MAPTILER_STYLE || 'streets-v2';
const mapTilerDarkStyle = import.meta.env.VITE_MAPTILER_DARK_STYLE || 'dataviz-dark';

const mapTilerAttribution =
  '&copy; <a href="https://www.maptiler.com/copyright/" target="_blank">MapTiler</a> ' +
  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>';

const mapTilerUrl = (style) =>
  `https://api.maptiler.com/maps/${style}/{z}/{x}/{y}.png?key=${mapTilerKey}`;

export const MAP_CONFIG = {
  defaultCenter: [20.5937, 78.9629], // India center
  defaultZoom: 5,
  minZoom: 4,
  maxZoom: 18,
  mapClassName: mapTilerKey ? 'maptiler-map' : 'dark-map',
  tileUrl: mapTilerKey
    ? mapTilerUrl(mapTilerLightStyle)
    : 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  attribution: mapTilerKey
    ? mapTilerAttribution
    : '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
  darkTileUrl: mapTilerKey
    ? mapTilerUrl(mapTilerDarkStyle)
    : 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
  darkAttribution: mapTilerKey
    ? mapTilerAttribution
    : '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/">CARTO</a>',
};

export const NGO_FALLBACK_IMAGE =
  'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400&auto=format&fit=crop';

export const NGO_LOCATIONS = [
  {
    id: 1,
    name: 'Education For All Foundation',
    lat: 19.076,
    lng: 72.8777,
    city: 'Mumbai',
    state: 'Maharashtra',
    address: '42, Andheri West, Mumbai 400058',
    phone: '+91 22 2634 5678',
    email: 'info@educationforall.org',
    activeCampaigns: 3,
    totalDonations: '₹12.5L',
    category: 'education',
    verified: true,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=400',
    description: 'Providing quality education to underprivileged children across Maharashtra.',
  },
  {
    id: 2,
    name: 'Rapid Relief India',
    lat: 28.6139,
    lng: 77.209,
    city: 'New Delhi',
    state: 'Delhi',
    address: '15, Connaught Place, New Delhi 110001',
    phone: '+91 11 2345 6789',
    email: 'help@rapidrelief.org',
    activeCampaigns: 5,
    totalDonations: '₹28.3L',
    category: 'disaster_relief',
    verified: true,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=400',
    description: 'Emergency disaster relief and rehabilitation services across India.',
  },
  {
    id: 3,
    name: 'Feed India Movement',
    lat: 12.9716,
    lng: 77.5946,
    city: 'Bangalore',
    state: 'Karnataka',
    address: '78, MG Road, Bangalore 560001',
    phone: '+91 80 4567 8901',
    email: 'contact@feedindia.org',
    activeCampaigns: 4,
    totalDonations: '₹18.7L',
    category: 'food',
    verified: true,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=400',
    description: 'Daily meal programs for homeless and underprivileged communities.',
  },
  {
    id: 4,
    name: 'WaterAid India',
    lat: 13.0827,
    lng: 80.2707,
    city: 'Chennai',
    state: 'Tamil Nadu',
    address: '23, T Nagar, Chennai 600017',
    phone: '+91 44 2890 1234',
    email: 'info@wateraidindia.org',
    activeCampaigns: 2,
    totalDonations: '₹9.2L',
    category: 'water',
    verified: true,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=400',
    description: 'Clean water initiatives and sanitation projects in rural communities.',
  },
  {
    id: 5,
    name: 'Health First NGO',
    lat: 22.5726,
    lng: 88.3639,
    city: 'Kolkata',
    state: 'West Bengal',
    address: '56, Park Street, Kolkata 700016',
    phone: '+91 33 2345 6780',
    email: 'support@healthfirst.org',
    activeCampaigns: 3,
    totalDonations: '₹15.1L',
    category: 'healthcare',
    verified: true,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=400',
    description: 'Healthcare services and medical camps for underserved communities.',
  },
  {
    id: 6,
    name: 'Warmth Foundation',
    lat: 26.9124,
    lng: 75.7873,
    city: 'Jaipur',
    state: 'Rajasthan',
    address: '34, MI Road, Jaipur 302001',
    phone: '+91 141 2567890',
    email: 'hello@warmthfoundation.org',
    activeCampaigns: 2,
    totalDonations: '₹6.8L',
    category: 'clothing',
    verified: true,
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400',
    description: 'Clothing drives and winter relief programs for communities in need.',
  },
  {
    id: 7,
    name: 'Green Earth Initiative',
    lat: 23.0225,
    lng: 72.5714,
    city: 'Ahmedabad',
    state: 'Gujarat',
    address: '89, CG Road, Ahmedabad 380006',
    phone: '+91 79 2678 9012',
    email: 'info@greenearth.org',
    activeCampaigns: 4,
    totalDonations: '₹11.4L',
    category: 'environment',
    verified: true,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=400',
    description: 'Environmental conservation and tree plantation drives.',
  },
  {
    id: 8,
    name: 'Women Empowerment Trust',
    lat: 17.385,
    lng: 78.4867,
    city: 'Hyderabad',
    state: 'Telangana',
    address: '45, Banjara Hills, Hyderabad 500034',
    phone: '+91 40 3456 7890',
    email: 'support@wet.org',
    activeCampaigns: 3,
    totalDonations: '₹13.6L',
    category: 'women',
    verified: true,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=400',
    description: 'Empowering women through skill development and education programs.',
  },
  {
    id: 9,
    name: 'Child Rights Foundation',
    lat: 18.5204,
    lng: 73.8567,
    city: 'Pune',
    state: 'Maharashtra',
    address: '67, FC Road, Pune 411004',
    phone: '+91 20 2567 8901',
    email: 'info@childrights.org',
    activeCampaigns: 2,
    totalDonations: '₹8.9L',
    category: 'children',
    verified: true,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?w=400',
    description: 'Protecting children\'s rights and providing shelter for homeless children.',
  },
  {
    id: 10,
    name: 'Rural Development Society',
    lat: 15.3173,
    lng: 75.7139,
    city: 'Hubli',
    state: 'Karnataka',
    address: '12, Station Road, Hubli 580020',
    phone: '+91 836 2345 678',
    email: 'info@ruraldevelopment.org',
    activeCampaigns: 3,
    totalDonations: '₹7.3L',
    category: 'rural',
    verified: true,
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1497486751825-1233686d5d80?w=400&auto=format&fit=crop',
    description: 'Comprehensive rural development programs across Karnataka.',
  },
];

export const PICKUP_LOCATIONS = [
  {
    id: 1,
    name: 'KindWave Mumbai Hub',
    lat: 19.076,
    lng: 72.8777,
    city: 'Mumbai',
    address: '123, Donation Center, Andheri West',
    type: 'pickup_center',
    timing: '9:00 AM - 6:00 PM',
    acceptedItems: ['clothes', 'food', 'books', 'medicine'],
    phone: '+91 22 1234 5678',
  },
  {
    id: 2,
    name: 'KindWave Delhi Hub',
    lat: 28.6139,
    lng: 77.209,
    city: 'New Delhi',
    address: '45, Collection Center, Connaught Place',
    type: 'pickup_center',
    timing: '10:00 AM - 7:00 PM',
    acceptedItems: ['clothes', 'food', 'books', 'medicine', 'other'],
    phone: '+91 11 2345 6789',
  },
  {
    id: 3,
    name: 'KindWave Bangalore Hub',
    lat: 12.9716,
    lng: 77.5946,
    city: 'Bangalore',
    address: '78, Drop-off Point, MG Road',
    type: 'pickup_center',
    timing: '9:30 AM - 6:30 PM',
    acceptedItems: ['clothes', 'food', 'books'],
    phone: '+91 80 4567 8901',
  },
];

export const CAMPAIGN_LOCATIONS = [
  {
    campaign_id: 1,
    title: 'Educate Underprivileged Children',
    lat: 19.0596,
    lng: 72.8295,
    city: 'Mumbai',
    beneficiaries: 500,
    status: 'active',
  },
  {
    campaign_id: 2,
    title: 'Disaster Relief: Flood Victims',
    lat: 25.3176,
    lng: 82.9739,
    city: 'Varanasi',
    beneficiaries: 2000,
    status: 'active',
  },
  {
    campaign_id: 3,
    title: 'Food for the Hungry',
    lat: 12.9716,
    lng: 77.5946,
    city: 'Bangalore',
    beneficiaries: 1500,
    status: 'active',
  },
  {
    campaign_id: 4,
    title: 'Clean Water Initiative',
    lat: 21.1458,
    lng: 79.0882,
    city: 'Nagpur',
    beneficiaries: 800,
    status: 'active',
  },
];

export const MAP_CATEGORIES = [
  { value: 'all', label: 'All', icon: '📍', color: '#3b82f6' },
  { value: 'education', label: 'Education', icon: '📚', color: '#8b5cf6' },
  { value: 'food', label: 'Food', icon: '🍲', color: '#f97316' },
  { value: 'healthcare', label: 'Healthcare', icon: '🏥', color: '#ef4444' },
  { value: 'water', label: 'Water', icon: '💧', color: '#06b6d4' },
  { value: 'disaster_relief', label: 'Disaster Relief', icon: '🆘', color: '#dc2626' },
  { value: 'clothing', label: 'Clothing', icon: '👕', color: '#14b8a6' },
  { value: 'environment', label: 'Environment', icon: '🌿', color: '#22c55e' },
  { value: 'women', label: 'Women', icon: '👩', color: '#ec4899' },
  { value: 'children', label: 'Children', icon: '👶', color: '#a855f7' },
  { value: 'rural', label: 'Rural', icon: '🏘️', color: '#eab308' },
];
